### ISSUE TITLE
On the science tab, don't work scroll by mouse wheel

### ISSUE THREAD

**Issue by Gen001** [scorzy/IdleSpace#17]
Scroll science by mouse wheel works only in a very narrow browser window.

**Comment by darkniko** [comment]
Yeah its kinda funny i have the same problem. Started playing with zoom in my browser seems when i go above 67%, from 75% and so on wheel scroll works just fine. Problem is beneath and including 67% it just stops working. BTW im using Opera.

**Comment by Gen001** [comment]
What help you need?
