### ISSUE TITLE
Robot C. Bug

### ISSUE THREAD

**Issue by Kingslayer9** [scorzy/IdleSpace#19]
These two images below is a before reload and after reload of my save. 

Before: https://prnt.sc/nwc5j3

After: https://prnt.sc/nwc6ef

As you can see, I not only lose around half of the multiplicative bonus, it also doesn't account for the Alloy and Energy Upkeep. 
Before I was making around 130 Robot C. Now I'm making 67.5 Robot C.

**Comment by scorzy** [comment]
Maybe because the prestige update? prestige bonus have been reset

**Comment by Arthree** [comment]
I think this was caused by Issue #22

**Comment by scorzy** [comment]
Probably solved with #22
