### ISSUE TITLE
Smart buy doesn't work for technicians

### ISSUE THREAD

**Issue by nyddogghr** [scorzy/IdleSpace#31]
Hi,

I noticed that smart buy doesn't work at least for technicians.
I've looked up at the code and it seems that https://github.com/scorzy/IdleSpace/blob/07d88e515a932378475e27dcf7946c10c4190be1/src/app/model/automators/robotEndingAutomator.ts#L24 is the line causing the issue.
I've changed it locally to `this.robot.operativity === 100` and technicians were smartly bought.

Could you take a look at this? 
Thanks

**Comment by scorzy** [comment]
Yes, fixed from the next version.
