### ISSUE TITLE
CANNOT RUN

### ISSUE THREAD

**Issue by LinXueyuanStdio** [scorzy/IdleSpace#36]
I run the following commands

```
npm i
npm start
```

but ir shows

![I5DE 4PJHWKZMGZPB2CT%YG](https://user-images.githubusercontent.com/23211526/64630088-f4a7e380-d426-11e9-9ee3-a65f2271b419.png)

the icon is tooooooo large

**Comment by scorzy** [comment]
i tried with a fresh install but mine was ok. What browser are you using?
there was any error during "npm i", especially about @clr/icons?

**Comment by LinXueyuanStdio** [comment]
oh i tried again and it was ok then.
there maybe something wrong with my typescript.
