### ISSUE TITLE
Prestige tree too small

### ISSUE THREAD

**Issue by scorzy** [scorzy/IdleSpace#7]
http://prntscr.com/njvehc Im on Opera - Windows. But i MUST rescale the browser zoom to 67%. If not the game is cut in half cause my screen is 10 inches

**Comment by darkniko** [comment]
yeah idk why that happens im now playing from chrome and see it just fine.

**Comment by darkniko** [comment]
BTW.. trying to deduce the command to enter in console to edit DM im just tired to try to reach 140 for A7 haha LOL

**Comment by scorzy** [comment]
closed beacause i will remove the canvas
